portfolio/portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('portfolioapp/', include('portfolioapp.urls')),
]

portfolio/portfolioapp/urls.py
from django.urls import path
from . import views
app_name='portfolioapp'
urlpatterns = [
    path('',views.general, name='general'),
    path('envoi/',views.envoi, name='envoi')

]

portfolio/portfolioapp/models.py
from django.db import models

class Commentaire(models.Model):
    mail = models.CharField(max_length=200)
    commentaire_text = models.CharField(max_length=2000)
    auteur = models.CharField(max_length=100)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.auteur
# Create your models here.

portfolio/portfolioapp/views.py
from django.shortcuts import render
from .models import Commentaire
import datetime
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

def general(request):
    latest_comm_list = Commentaire.objects.order_by('-pub_date')[:5]
    context = {'latest_comm_list': latest_comm_list}
    return render(request, 'portfolioapp/index.html', context)
# Create your views here.

def envoi(request):

    comm_text = request.POST.get('comm','NoText')
    comm_auteur = request.POST.get('commaut','Guest')
    comm_mail = request.POST.get('commmail','Guest')
    comm_date = datetime.datetime.now().date()
#    try:
    comm = Commentaire(auteur=comm_auteur,commentaire_text=comm_text,mail=comm_mail,pub_date=comm_date)
#    except (comm_text==''):
#        # Redisplay the question voting form.
#        return render(request, 'portfolio/index.html', {
#            'error_message': "You didn't select a message.",
#        })
#    else:
    comm.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
    return HttpResponseRedirect(reverse('portfolioapp:general'))

portfolio/portfolioapp/templates/portfolioapp/index.html
<html>
   <head>
      <meta charset="UTF-8">
      <title>Colin THOMAS : Portfolio</title>
      <meta name = "description" content = "Portfolio des projets informatiques de THOMAS Colin">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css">
      {% load static %}
      <link rel="stylesheet" type="text/css" href="{% static 'portfolioapp/style.css' %}">
      <link rel="shortcut icon" type="image/png" href="{% static 'media/favicon.ico' %}"/>
      <script type="application/javascript" src="https://unpkg.com/react@16.0.0/umd/react.production.min.js"></script>
      <script type="application/javascript" src="https://unpkg.com/react-dom@16.0.0/umd/react-dom.production.min.js"></script>
      <script type="application/javascript" src="https://unpkg.com/babel-standalone@6.26.0/babel.js"></script>
      
      <script type="text/babel" src="{% static 'portfolioapp/test.js' %}?version=2"></script>
      <script type="text/babel" src="{% static 'portfolioapp/propos.js' %}?version=2"></script>
      <script type="text/babel" src="{% static 'portfolioapp/projets.js' %}?version=2"></script>
      <script type="text/babel" src="{% static 'portfolioapp/divers.js' %}?version=2"></script>
      
   </head>
   <body>
      <header>
         <nav>
            <ul>
               <li id="logo"><a href="#">Colin</a></li>
               <li><a href="#contact">Me contacter</a></li>
               <li><a href="#projets">Mes projets informatiques</a></li>
            </ul>
         </nav>
         <div id="imagePrincipale">
            <h1>Page personnelle</h1>
            <div id="premierTrait"></div>
            <h3>Colin THOMAS</h3>
         </div>
      </header>
      <div id="propos"></div>
      <div class="projets" id="projets"></div>
      <div class="divers" id="divers"></div>
      <footer id="footer">
         <h2 id="contact">Me contacter</h2>
         <h4 id="contact2">Laissez-moi un commentaire, une question, dites-moi quand vous êtes libres pour prendre un thé...</h4>
         <form action="{% url 'portfolioapp:envoi' %}" method="post">
            {% csrf_token %}
            <table>
               <tbody>
                  <tr>
                     <td><input name="comm" id="name" placeholder="Nom"></td>
                     <td><input name="commmail" id="mail" placeholder="E-mail"></td>
                  </tr>
                  <tr>
                     <td colspan=2> <input name="commaut" id="corps" placeholder="Votre message ici..."></td>
                  </tr>
                  <tr>
                     <td colspan=2><input type="submit" value="Envoyer"></td>
                  </tr>
               </tbody>
            </table>

         </form>
         {% if latest_comm_list %}
         <ul>
            {% for Commentaire in latest_comm_list %}
            <li>
               {{ Commentaire.auteur }}
            </li>
            <li>
               {{ Commentaire.pub_date }}
            </li>
            <li style="padding-bottom:10px">
               {{ Commentaire.commentaire_text }}
            </li>
            {% endfor %}
         </ul>
         {% else %}
         <p>Aucun commentaire n'a été rédigé pour l'instant.</p>
         {% endif %}
         <div id="deuxiemeTrait"></div>
         <div id="copyrightEtIcons">
            <div id="copyright">
               <span>© THOMASColin; 2021</span>
            </div>
         </div>
      </footer>
      
      <script type="text/babel" src="{% static 'portfolioapp/test.js' %}"></script>
      <script type="text/babel" src="{% static 'portfolioapp/propos.js' %}"></script>
      <script type="text/babel" src="{% static 'portfolioapp/projets.js' %}"></script>
      <script type="text/babel" src="{% static 'portfolioapp/divers.js' %}"></script>